//! Original experiment inputs through the actual production planner/classifier.
use super::*;
use qualification::{admitted_runtime, request_value, save};
use sha2::{Digest, Sha256};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

const MANIFEST: &str = include_str!("fixtures/c9-parity-manifest.json");
const MANIFEST_SHA: &str = "c3d186a65d3a28183ed6bd39fb70b3c74b081f6d41a3ba2482902fa79c6937af";

fn hash(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn manifest() -> Value {
    assert_eq!(hash(MANIFEST.as_bytes()), MANIFEST_SHA);
    serde_json::from_str(MANIFEST).unwrap()
}

#[test]
fn original_c9_manifest_bytes_remain_frozen() {
    assert_eq!(hash(MANIFEST.as_bytes()), MANIFEST_SHA);
}

fn records(m: &Value, f: &Value) -> Result<Vec<Value>, &'static str> {
    if m != &manifest() {
        return Err("manifest/labels changed");
    }
    if hash(
        f["system_prompt"]
            .as_str()
            .ok_or("system missing")?
            .as_bytes(),
    ) != m["system_prompt_sha256"]
    {
        return Err("historical instruction changed");
    }
    let mut ordered = Vec::new();
    let all = f["records"].as_array().ok_or("records missing")?;
    for label in m["cases"].as_array().ok_or("cases missing")? {
        let matches: Vec<_> = all.iter().filter(|r| r["case"] == label["case"]).collect();
        if matches.len() != 1 {
            return Err("missing/duplicate case");
        }
        let record = matches[0];
        if hash(&serde_json::to_vec(record).unwrap()) != label["record_sha256"] {
            return Err("original input/output/label changed");
        }
        ordered.push(record.clone());
    }
    if ordered.len() != 30 {
        return Err("original set incomplete");
    }
    Ok(ordered)
}

fn projection(record: &Value, runtime: &dyn ModelRuntime) -> Vec<VerificationBatch> {
    let (prompt, claims) = input(record);
    let original = &record["user_prompt"];
    assert_eq!(prompt.claims.len(), 1);
    assert_eq!(prompt.claims[0].text, original["claims"][0]["text"]);
    assert!(prompt.claims[0].source_framing.is_none());
    let expected = original["claims"][0]["evidence"].as_array().unwrap();
    assert_eq!(prompt.claims[0].evidence.len(), expected.len());
    for (actual, expected) in prompt.claims[0].evidence.iter().zip(expected) {
        assert_eq!(actual.evidence_id, expected["evidence_id"]);
        assert_eq!(actual.exact_quote, expected["exact_quote"]);
        let context = original["clause_contexts"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["context_id"] == expected["clause_context_id"])
            .unwrap();
        assert_eq!(
            actual.full_clause.as_deref().unwrap(),
            context["full_clause"]
        );
    }
    let batches = plan(runtime, &prompt, &claims, 8).unwrap();
    assert_eq!(batches.len(), 1, "original whole-claim joint projection");
    for batch in &batches {
        let wire: Value = serde_json::from_str(&batch.user_prompt).unwrap();
        assert!(wire.get("parent_claim_context").is_none());
        for key in [
            "parent_claim_context",
            "dimension",
            "source_segments",
            "claim_segments",
        ] {
            assert!(
                wire.get(key).is_none(),
                "superseded projection field: {key}"
            );
        }
        // IDs are regenerated by the owning identifier projection. Compare the
        // source associations after resolving IDs, never by matching words.
        assert_eq!(wire["claims"][0]["text"], original["claims"][0]["text"]);
        let emitted = wire["claims"][0]["evidence"].as_array().unwrap();
        assert_eq!(emitted.len(), expected.len());
        for (actual, expected) in emitted.iter().zip(expected) {
            assert_eq!(actual["exact_quote"], expected["exact_quote"]);
            let lookup = |value: &Value, id: &Value| {
                value["clause_contexts"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .find(|c| c["context_id"] == *id)
                    .unwrap()["full_clause"]
                    .clone()
            };
            assert_eq!(
                lookup(&wire, &actual["clause_context_id"]),
                lookup(original, &expected["clause_context_id"])
            );
        }
    }
    batches
}

fn observation(
    label: &Value,
    record: &Value,
    prepared: &[Prepared],
    responses: &[Value],
    actual: Option<ClaimVerdict>,
) -> Value {
    let historical: Value = serde_json::from_str(record["raw_response"].as_str().unwrap()).unwrap();
    let text = responses
        .first()
        .and_then(|r| r["text"].as_str())
        .unwrap_or("");
    let raw: Value = serde_json::from_str(text).unwrap_or(Value::Null);
    let parsed = prepared.first().and_then(|p| p.parse(text, &p.claim).ok());
    let valid = prepared.len() == 1
        && responses.len() == 1
        && parsed
            .as_ref()
            .is_some_and(|p| Some(&p.verdict) == actual.as_ref());
    let mut relations = Vec::new();
    for dimension in DIMENSIONS {
        let comparison = &raw["verdicts"][0]["comparisons"][dimension];
        let typed = serde_json::from_value::<Comparison>(comparison.clone()).ok();
        let owned = typed
            .as_ref()
            .zip(prepared.first())
            .is_some_and(|(c, p)| c.owned_by(p));
        let relation_valid = typed.as_ref().is_some_and(Comparison::relation_valid);
        let reference = &historical["verdicts"][0]["comparisons"][dimension];
        let mut passages = Vec::new();
        for side in ["source_spans", "claim_spans"] {
            for span in reference[side].as_array().unwrap() {
                let found = comparison[side].as_array().is_some_and(|selected| {
                    selected.iter().any(|p| {
                        p.as_str()
                            .is_some_and(|p| piece_covers_reference(p, span.as_str().unwrap()))
                    })
                });
                passages.push(
                    json!({"side":side,"reference":span,"contained_in_selected_piece":found}),
                );
            }
        }
        relations.push(json!({"dimension":dimension,"owned_passages_valid":owned,"relation_valid":relation_valid,"recorded_relation":reference["relation"],"actual_relation":comparison["relation"],"relation_equal":comparison["relation"]==reference["relation"],"passages":passages}));
    }
    let actual_json = json!(actual);
    let exact = actual.is_some() && actual_json == label["expected_parity_verdict"];
    let semantic = match label["adjudicated_expected_admit"].as_bool() {
        Some(expected) => actual
            .as_ref()
            .is_some_and(|v| (*v == ClaimVerdict::Supported) == expected),
        None => true,
    };
    json!({"case":label["case"],"actual_verdict":actual_json,"expected_verdict":label["expected_parity_verdict"],"label_status":label["label_status"],"semantic_label_passed":semantic,"exact_verdict_parity":exact,"delivery_parity":actual.as_ref().is_some_and(|v|(*v==ClaimVerdict::Supported)==(label["expected_parity_verdict"]=="supported")),"valid":valid,"passed":valid&&exact&&semantic,"relations":relations,"source_relevance":"original references retained; differences require review"})
}

fn score(m: &Value, rows: &[Value]) -> bool {
    let expected = m["cases"].as_array().unwrap();
    rows.len() == expected.len()
        && rows
            .iter()
            .zip(expected)
            .all(|(row, label)| row["case"] == label["case"] && row["passed"] == true)
}

#[test]
fn original_manifest_and_production_projection_are_complete() {
    let m = manifest();
    let records = records(&m, &fixture()).unwrap();
    let calls: usize = records
        .iter()
        .map(|r| projection(r, &Runtime::default()).len())
        .sum();
    assert_eq!(calls, 30);
    println!(
        "C9_PARITY_STATIC cases={} calls={} generation_calls=0",
        records.len(),
        calls
    );
}

#[test]
fn parity_restores_original_joint_excerpt_requests() {
    let m = manifest();
    let f = fixture();
    for record in records(&m, &f).unwrap() {
        let (prompt, claims) = input(&record);
        let batches = plan(&Runtime::default(), &prompt, &claims, 8).unwrap();
        assert_eq!(
            batches.len(),
            1,
            "original joint C9 projection required: {}",
            record["case"]
        );
        let request = verification_request(&batches[0], 0, 7);
        assert_eq!(request.system_prompt, f["system_prompt"].as_str().unwrap());
        assert_eq!(
            request.user_prompt,
            serde_json::to_string(&record["user_prompt"]).unwrap()
        );
        assert_eq!(
            hash(&serde_json::to_vec(&batches[0].comparison.as_ref().unwrap().schema).unwrap()),
            record["schema_sha256"]
        );
    }
}

#[test]
fn parity_manifest_rejects_missing_duplicate_and_altered_evidence() {
    let m = manifest();
    let f = fixture();
    let mut bad = f.clone();
    bad["records"].as_array_mut().unwrap().remove(0);
    assert!(records(&m, &bad).is_err());
    let mut bad = f.clone();
    let first = bad["records"][0].clone();
    bad["records"].as_array_mut().unwrap().push(first);
    assert!(records(&m, &bad).is_err());
    for key in ["user_prompt", "raw_response", "recorded_verdict"] {
        let mut bad = f.clone();
        bad["records"][0][key] = Value::Null;
        assert!(records(&m, &bad).is_err());
    }
    let mut bad = m.clone();
    bad["cases"][0]["adjudicated_expected_admit"] = json!(true);
    assert!(records(&bad, &f).is_err());
}

#[test]
fn parity_scoring_preserves_exact_verdict_and_valid_relation_requirements() {
    let m = manifest();
    let records = records(&m, &fixture()).unwrap();
    let mut rows = Vec::new();
    for (label, record) in m["cases"].as_array().unwrap().iter().zip(&records) {
        let batches = projection(record, &Runtime::default());
        let wanted: ClaimVerdict =
            serde_json::from_value(label["expected_parity_verdict"].clone()).unwrap();
        let responses: Vec<_> = batches
            .iter()
            .map(|b| json!({"text":fixture_verdict_response(&verification_request(b,0,7),wanted.clone())}))
            .collect();
        let prepared: Vec<_> = batches
            .iter()
            .map(|b| b.comparison.clone().unwrap())
            .collect();
        let row = observation(label, record, &prepared, &responses, Some(wanted.clone()));
        assert_eq!(row["passed"], true);
        rows.push(row);
        for wrong in [
            ClaimVerdict::Supported,
            ClaimVerdict::Unsupported,
            ClaimVerdict::Ambiguous,
        ]
        .into_iter()
        .filter(|v| *v != wanted)
        {
            assert_eq!(
                observation(label, record, &prepared, &responses, Some(wrong))["passed"],
                false
            );
        }
        assert_eq!(
            observation(label, record, &prepared, &[], Some(wanted.clone()))["passed"],
            false
        );
        for (i, dimension) in DIMENSIONS.iter().enumerate() {
            let mut invalid = responses.clone();
            let mut raw: Value =
                serde_json::from_str(invalid[0]["text"].as_str().unwrap()).unwrap();
            raw["verdicts"][0]["comparisons"][dimension] =
                json!({"source_spans":[],"claim_spans":[],"relation":"preserved"});
            invalid[0]["text"] = json!(raw.to_string());
            let row = observation(label, record, &prepared, &invalid, Some(wanted.clone()));
            assert_eq!(row["passed"], false);
            assert_eq!(row["relations"][i]["owned_passages_valid"], true);
            assert_eq!(row["relations"][i]["relation_valid"], false);
            raw["verdicts"][0]["comparisons"][dimension] = json!({"source_spans":["invented"],"claim_spans":["invented"],"relation":"preserved"});
            invalid[0]["text"] = json!(raw.to_string());
            let row = observation(label, record, &prepared, &invalid, Some(wanted.clone()));
            assert_eq!(row["passed"], false);
            assert_eq!(row["relations"][i]["owned_passages_valid"], false);
            assert_eq!(row["relations"][i]["relation_valid"], true);
        }
    }
    assert!(score(&m, &rows));
    assert!(!score(&m, &[]));
    assert!(!score(&m, &rows[..29]));
    let mut duplicate = rows.clone();
    duplicate.push(rows[0].clone());
    assert!(!score(&m, &duplicate));
    rows.swap(0, 1);
    assert!(!score(&m, &rows));
}

struct Recording {
    inner: Arc<dyn ModelRuntime>,
    allowed: Vec<ModelRequest>,
    output: PathBuf,
    responses: Mutex<Vec<Value>>,
    owner: String,
    deployment: String,
    policy: u32,
    process: Value,
}

fn gateway_process() -> Value {
    let result = std::process::Command::new("systemctl")
        .args([
            "show",
            "local-inference-gateway.service",
            "-p",
            "ActiveState",
            "-p",
            "SubState",
            "-p",
            "MainPID",
            "-p",
            "ExecMainStartTimestamp",
            "-p",
            "ExecMainStartTimestampMonotonic",
        ])
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "gateway process identity unavailable"
    );
    let text = String::from_utf8(result.stdout).unwrap();
    let fields: serde_json::Map<String, Value> = text
        .lines()
        .map(|line| {
            let (key, value) = line.split_once('=').unwrap();
            (key.into(), json!(value))
        })
        .collect();
    Value::Object(fields)
}
impl ModelRuntime for Recording {
    fn generate(&self, r: &ModelRequest) -> Result<ModelResponse, ModelRuntimeFailure> {
        self.generate_with_control(r, &UNCONTROLLED_EXECUTION)
    }
    fn generate_with_control(
        &self,
        r: &ModelRequest,
        c: &dyn ExecutionControl,
    ) -> Result<ModelResponse, ModelRuntimeFailure> {
        let mut rows = self.responses.lock().unwrap();
        let i = rows.len();
        assert_eq!(self.allowed.get(i), Some(r), "changed/extra request");
        assert_eq!(
            gateway_process(),
            self.process,
            "gateway process changed before request"
        );
        save(
            &self.output.join(format!("request-{i}.json")),
            &request_value(r),
        );
        let started = std::time::Instant::now();
        let result = self.inner.generate_with_control(r, c);
        let mut row = match &result {
            Ok(v) => {
                json!({"text":v.text,"runtime_id":v.runtime_id,"model_id":v.model_id,"request_attempts":v.request_attempts,"output_bytes":v.text.len(),"output_characters":v.text.chars().count()})
            }
            Err(e) => {
                json!({"error":e.code,"message":e.message,"request_attempts":e.request_attempts})
            }
        };
        row["milliseconds"] = json!(started.elapsed().as_millis());
        row["ordinal"] = json!(r.ordinal);
        save(&self.output.join(format!("response-{i}.json")), &row);
        rows.push(row);
        assert_eq!(
            gateway_process(),
            self.process,
            "gateway process changed during request"
        );
        if let Ok(response) = &result {
            use crate::pipeline::gateway_store::{load_request, GatewayRequestKey};
            let conn =
                rusqlite::Connection::open(self.output.join("gateway-ledger.sqlite")).unwrap();
            let completion = load_request(
                &conn,
                &GatewayRequestKey {
                    owner_id: self.owner.clone(),
                    stage: r.stage.clone(),
                    ordinal: r.ordinal,
                },
            )
            .unwrap()
            .unwrap()
            .completion
            .unwrap();
            assert_eq!(
                completion.deployment_id, self.deployment,
                "deployment changed"
            );
            assert_eq!(
                completion.task_policy_version, self.policy,
                "policy changed"
            );
            assert_eq!(completion.content, response.text, "stored response differs");
            save(
                &self.output.join(format!("provenance-{i}.json")),
                &serde_json::to_value(completion).unwrap(),
            );
        }
        result
    }
    fn health(&self) -> Result<(), ModelRuntimeFailure> {
        self.inner.health()
    }
    fn runtime_id(&self) -> &str {
        self.inner.runtime_id()
    }
    fn model_id(&self) -> &str {
        self.inner.model_id()
    }
    fn context_tokens(&self, s: PipelineStage) -> u32 {
        self.inner.context_tokens(s)
    }
    fn preflight_request(&self, r: &ModelRequest) -> Result<(), ModelRuntimeFailure> {
        self.inner.preflight_request(r)
    }
    fn supports_response_schema(&self, n: &str) -> bool {
        self.inner.supports_response_schema(n)
    }
    fn response_schema_byte_limit(&self, s: PipelineStage, n: &str) -> usize {
        self.inner.response_schema_byte_limit(s, n)
    }
}

#[test]
#[ignore = "accepted parity contract, frozen receipt and exclusive inference lock; exactly 30 calls"]
fn original_c9_production_gateway_parity() {
    let out = PathBuf::from(std::env::var("DOC_SUM_C9_PARITY_OUTPUT").unwrap());
    let m = manifest();
    let records = records(&m, &fixture()).unwrap();
    let scratch = tempfile::tempdir().unwrap();
    let inner = admitted_runtime(&out, "gateway", scratch.path());
    let mut plans = Vec::new();
    let mut allowed = Vec::new();
    let mut costs = Vec::new();
    for record in &records {
        let batches = projection(record, inner.as_ref());
        for batch in &batches {
            let r = verification_request(batch, allowed.len() as u32, 7);
            let admit = inner.preflight_request(&r);
            costs.push(json!({"case":record["case"],"ordinal":r.ordinal,"admitted":admit.is_ok(),"error":admit.err().map(|e|e.code)}));
            save(
                &out.join(format!("planned-{}.json", r.ordinal)),
                &request_value(&r),
            );
            allowed.push(r);
        }
        plans.push(batches);
    }
    let admitted = allowed.len() == 30 && costs.iter().all(|c| c["admitted"] == true);
    save(
        &out.join("admission.json"),
        &json!({"admitted":admitted,"calls":allowed.len(),"cases":costs,"generation_calls":0}),
    );
    assert!(admitted, "stop before generation on admission failure");
    if std::env::var("DOC_SUM_C9_BOUNDARIES_ONLY").as_deref() == Ok("1") {
        return;
    }
    let identity: Value =
        serde_json::from_slice(&std::fs::read(out.join("runtime.json")).unwrap()).unwrap();
    let runtime = Recording {
        inner,
        allowed,
        output: out.clone(),
        responses: Mutex::new(Vec::new()),
        owner: identity["fresh_owner"].as_str().unwrap().into(),
        deployment: std::env::var("DOC_SUM_C9_DEPLOYMENT").unwrap(),
        policy: std::env::var("DOC_SUM_C9_POLICY").unwrap().parse().unwrap(),
        process: serde_json::from_str(&std::env::var("DOC_SUM_C9_PROCESS").unwrap()).unwrap(),
    };
    let mut ordinal = 0;
    let mut observations = Vec::new();
    for ((label, record), batches) in m["cases"]
        .as_array()
        .unwrap()
        .iter()
        .zip(&records)
        .zip(plans)
    {
        let prepared: Vec<_> = batches
            .iter()
            .map(|b| b.comparison.clone().unwrap())
            .collect();
        let start = runtime.responses.lock().unwrap().len();
        let result = classify_verification_batches(
            &runtime,
            batches,
            7,
            &mut ordinal,
            &UNCONTROLLED_EXECUTION,
        );
        let actual = result
            .as_ref()
            .ok()
            .and_then(|v| v.first())
            .map(|v| v.verdict.clone());
        let responses = runtime.responses.lock().unwrap();
        let row = observation(label, record, &prepared, &responses[start..], actual);
        save(
            &out.join(format!(
                "case-{}.json",
                label["historical_index"].as_u64().unwrap()
            )),
            &row,
        );
        println!(
            "C9_PARITY_CASE {}",
            json!({"case":label["case"],"actual":row["actual_verdict"],"expected":row["expected_verdict"],"passed":row["passed"]})
        );
        observations.push(row);
        if result.is_err() {
            break;
        }
    }
    let calls = runtime.responses.lock().unwrap().len();
    let passed = score(&m, &observations) && calls == 30;
    save(
        &out.join("results.json"),
        &json!({"gateway_parity_passed":passed,"actual_calls":calls,"cases":observations,"manifest_sha256":MANIFEST_SHA}),
    );
    println!("C9_PARITY_RESULT calls={calls} passed={passed}");
}
